### ISSUE TITLE
enhancement: Archive unit test results when run-tests = true

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-community-hub/community-action-maven-release#34]
When I set `run-tests` to `true` the workflow will execute the unit tests for me. However, if any of the tests happen to fail, it will not archive the test results. Therefore I'd have to look into the build logs manually to see what went wrong. It'd be a nice addition if we could add an archiving step to this action.

This would mean we need to archive and publish the results on failure, something like:
```yaml
      - name: Archive Test Results on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 7

      - name: Publish Unit Test Results
        id: publish
        uses: EnricoMi/publish-unit-test-result-action@v1.25
        if: failure()
        with:
          files: target/surefire-reports/*.xml
```
