### ISSUE TITLE
Adding artifacts on Github does not work

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/community-action-maven-release#52]
See https://github.com/camunda-community-hub/community-hub-extension-example/actions/runs/4062895558/jobs/6994482279#step:5:1410 - this currently doesn't work.

Looks you (@zambrovski ) add files to the Github env in the action: 

```
    - name: Archive artifacts
      id: create-archive
      run: |-
        test -z "${{ inputs.artifacts-pattern }}" && echo "::debug::Skipping archiving because artifacts-pattern is unset" && exit 0
        # Filename: [repo without org]-[version].zip
        ZIPFILE=${GITHUB_REPOSITORY#*/}-${{ inputs.release-version }}.zip
        zip $ZIPFILE $(find . -path ${{ inputs.artifacts-pattern }})
        echo "filename=${ZIPFILE}" >> $GITHUB_ENV
      shell: bash
```

This was different in an older version of the action: https://github.com/camunda-community-hub/community-action-maven-release/blob/a7af046fe7badb05a6a91e8e8fc014518957381f/action.yml#L162

And the workflow actually would require the output to be used. 

```
      - if: github.event.release
        name: Attach artifacts to GitHub Release (Release only)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_name: ${{ steps.release.outputs.artifacts_archive_path }}
          asset_content_type: application/zip
```

Shall I revert that change to the original version to make the workflow work again @zambrovski ?
